name = "Create Aero Salvage Op"
author = "MelodicCougar7, AwDavid"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "464d19509fef4f1d6b4dab2be5bf1147f90d58a75e3258b67a348044304e3320"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
