name = "Create Aero Salvage Op"
author = "MelodicCougar7, AwDavid"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebf3de2260f63e9a5ce5ed740dcbbb052932783b2fb986b00c1c652112a9cdfc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
