name = "Create Aero Salvage Op"
author = "MelodicCougar7, AwDavid"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce34ee69e63a0fc265d2e45c6078c3a054774140a8aee2d23a4e561ff41e0ecd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
